name: hm_video_downloader
description: A new Flutter project.

publish_to: 'none'
version: 1.1.0+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  chewie: ^1.3.1
  dio: ^4.0.4
  file_manager: ^1.0.0
  file_sizes: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_video_info: ^1.2.0
  fluttericon: ^2.0.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  in_app_review: ^2.0.4
  in_app_update: ^3.0.0
  insta_extractor: ^0.0.5
  intl: ^0.17.0
  launch_review: ^3.0.1
  modal_bottom_sheet: ^2.0.1
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  share_plus: ^3.1.0
  storage_space: ^1.0.1+5
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  video_player: ^2.3.0
  water_drop_nav_bar: ^2.1.0+8

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.0.1

flutter:

  uses-material-design: true
