name: hm_video_downloader
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  chewie: ^1.3.1
  dio: ^4.0.4
  file_manager: ^1.0.0
  file_sizes: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_video_info: ^1.2.0
  fluttericon: ^2.0.0
  google_fonts: ^2.3.1
  google_mobile_ads: ^1.1.0
  http: ^0.13.4
  insta_extractor: ^0.0.5
  intl: ^0.17.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  share_plus: ^3.1.0
  storage_space: ^1.0.1+5
  timeago: ^3.2.2
  video_player: ^2.3.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.0.1

flutter:

  uses-material-design: true
